./rtl/jtag_defines.sv
./rtl/jtag_package.sv
./rtl/jtag_interface.sv
./rtl/TAP_FSM.sv
./rtl/shift_register.sv
./rtl/bsc.sv
./rtl/instr_register.sv
./rtl/instr_decoder.sv
./rtl/TDR.sv
./rtl/JTAG_top.sv
./tb/jtag_tb_top.sv
